Lab 2
avbmfff/software_design pull request #2
Opened 2024-09-30 16:06 UTC by EllaSlep

2024-10-02 08:06 UTC, vekajp requested changes

2024-10-02 08:06 UTC, vekajp commented on README.md
> +19. <span style="color:purple">Какие атрибуты есть у задачи, кроме названия, статуса и исполнителей? Например, сроки выполнения задачи, приоритет, градация исполнителей (исполнитель/проверяющий/ответ
про комментарии нет в вопросах и требованиях, не нужно додумывать, иначе придется с вас это спрашивать когда дойдет дело до реализации

2024-10-02 08:06 UTC, vekajp commented on README.md
> +| Уведомление (Notification) | Оповещение пользователя о событиях в проекте или задаче | Текст уведомления, тип уведомления (система/внешний сервис), отправитель, получатель | Пользователь, проект, з
уведомления тоже non-mvp, но если оставите - придется делать

2024-10-02 08:06 UTC, vekajp commented on README.md
> +
если упоминаете объект в Ассоциированные термины, то нужно давать ему описание как термину

2024-10-02 08:06 UTC, vekajp commented on README.md
> +| Управление проектами | В этом случае пользователь будет ответственным. Он будет следить за выполнением задач, но не редактировать их | User<br> • name<br> • nikname <br><br> Project<br> • name<br>
а в какой контекст вы бы поместили авторизацию или поиск пользователей? и почему?

2024-10-04 18:27 UTC, avbmfff commented on README.md
> +19. <span style="color:purple">Какие атрибуты есть у задачи, кроме названия, статуса и исполнителей? Например, сроки выполнения задачи, приоритет, градация исполнителей (исполнитель/проверяющий/ответ
убрали комментарии из ТЗ

2024-10-04 18:27 UTC, avbmfff commented on README.md
> +| Уведомление (Notification) | Оповещение пользователя о событиях в проекте или задаче | Текст уведомления, тип уведомления (система/внешний сервис), отправитель, получатель | Пользователь, проект, з
убрали уведомления из ТЗ

2024-10-04 18:27 UTC, avbmfff commented on README.md
> +
done

2024-10-04 18:27 UTC, avbmfff commented on README.md
> +| Управление проектами | В этом случае пользователь будет ответственным. Он будет следить за выполнением задач, но не редактировать их | User<br> • name<br> • nikname <br><br> Project<br> • name<br>
done. 
Поместили во "Взаимодействие с системой", так как это не связано напрямую с проектами и задачами и мы оперируем просто пользователями, а не исполнителями (ответственными)

2024-10-14 17:41 UTC, merged