Lab 5
avbmfff/software_design pull request #5
Opened 2024-10-18 19:46 UTC by EllaSlep

2024-10-21 17:06 UTC, vekajp requested changes

2024-10-21 17:06 UTC, vekajp commented on README.md
> +21. $${\color{purple} \textbf{Может пользователь редактировать/удалить задачи? Если да, то может ли это сделать любой пользователь или, например, только исполнитель или создатель задачи? Если ли огра
неудбно смотреть пул реквест когда есть изменения, не несущие смысл по заданию. Лучше их катить отдельно

2024-10-21 17:06 UTC, vekajp commented on README.md
> +21. $${\color{purple} \textbf{Может пользователь редактировать/удалить задачи? Если да, то может ли это сделать любой пользователь или, например, только исполнитель или создатель задачи? Если ли огра
мб я не особо понимаю смысл этих изменения

2024-10-21 17:06 UTC, vekajp commented on README.md
> +| [2](#фт2) | User: никнейм, имя и пароль  | createUser(id, nickname, name, password) | UserCreatedEvent | Да (поиск пользвателей) |
продублируйте текстом требования в таблицу

2024-10-21 17:06 UTC, vekajp commented on README.md
> +| [2](#фт2) | User: никнейм, имя и пароль  | createUser(id, nickname, name, password) | UserCreatedEvent | Да (поиск пользвателей) |
вы пробовали переходить по ссылке из пра? Норм отображается?

2024-10-21 17:06 UTC, vekajp commented on README.md
> +
проекты мы не обновляем разве?

2024-11-22 18:50 UTC, avbmfff commented on README.md
> +
У нас обновляются составные части проекта. Можно ли считать, что таким образом обновляется сам проект?

2024-11-22 19:17 UTC, merged