Lab 7
avbmfff/software_design pull request #6
Opened 2024-11-18 14:50 UTC by EllaSlep

2024-11-20 11:43 UTC, vekajp requested changes

2024-11-20 11:43 UTC, vekajp commented on README.md
> +| [1](#фт1) | User |
не кликается, прописать текстом

2024-11-20 11:43 UTC, vekajp commented on README.md
> +Первые 3 пункта были выполнены в предыдущей лабораторной работе, так что перейдем к пунктам 4 и 5
в таблице в строке 359 нет контекстов

2024-11-20 11:43 UTC, vekajp commented on README.md
> +| Задачи | ID, name, users, status, date_till, priority, event, event_date |
users что за структура?

2024-11-20 11:43 UTC, vekajp commented on README.md
> +
поиск пользователя по никнейму есть среди функциональных требований

2024-11-20 11:43 UTC, vekajp commented on README.md
> +| Задачи | ID, name, users, status, date_till, priority, event, event_date |
исполнитель?

2024-11-20 11:43 UTC, vekajp commented on README.md
> +
статусы проекта?

2024-11-20 11:43 UTC, vekajp commented on README.md
> +Первые 3 пункта были выполнены в предыдущей лабораторной работе, так что перейдем к пунктам 4 и 5
в таком виде не удобно смотреть лабораторную работу, не указали где именно лежит то, что вы делали в предыдущих работах
Ссылки не тыкаются, вы бы проверили перед сдачей пра на ревью

2024-11-22 18:49 UTC, avbmfff commented on README.md
> +| [1](#фт1) | User |
Ссылки кликабельны, если смотреть в режиме превью для файлов маркдаун. Скорее всего вы смотрите в режиме кода, поэтому переходы по ссылкам не работают.

2024-11-22 19:00 UTC, avbmfff commented on README.md
> +Первые 3 пункта были выполнены в предыдущей лабораторной работе, так что перейдем к пунктам 4 и 5
https://github.com/avbmfff/software_design/pull/6#discussion_r1854496087

2024-11-22 20:05 UTC, avbmfff commented on README.md
> +| Задачи | ID, name, users, status, date_till, priority, event, event_date |
Это список пользователей, работающих над задачей (исполнители)

2024-11-22 20:09 UTC, avbmfff commented on README.md
> +
https://github.com/avbmfff/software_design/pull/6#discussion_r1850166404 Да, он у нас присуствует и добален в проект. 
https://github.com/avbmfff/software_design/pull/6#discussion_r1850168904 Это пул возможных статусов внутри проекта.

2024-11-22 20:33 UTC, merged